### ISSUE TITLE
Add catch-all issue template

### ISSUE THREAD

**Issue by maxhawkins** [pion/.github#2]
## Summary

Only bug report and feature request are listed. There should be a third template for general issues.

## Motivation

Not all issues fit into the two categories, so it can be confusing where to file

**Comment by Sean-Der** [comment]
Hey @maxhawkins if you create a new template in here it should show up in all projects under Pions organization.

Thanks for pointing this out, hopefully we haven't created a funnel where we are losing tickets :(

One thing I have noticed is that quality of tickets are getting A LOT better. I haven't triaged a ticket recently that wasn't a Pion issue.

**Comment by Sean-Der** [comment]
Hey @maxhawkins 

Recently I have been driving everyone to Slack, and it seems like it has been successful. If people communicate in Slack others will get involved. For GitHub issues I am really the only person responding/triaging.

If you think I am missing something here please re-open!
